version: '3.8'

services:
  app:
    build: .
    ports:
      - "3005:3000"
    environment:
      - NODE_ENV=production
      - APP_PORT=3000
    depends_on:
      - postgres
      - mysql
      - mongodb
      - redis
    restart: unless-stopped
    networks:
      - rps-network

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: rps_ai_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - rps-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: simak_db
      MYSQL_USER: simak_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - rps-network

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - rps-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - rps-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - rps-network

volumes:
  postgres_data:
  mysql_data:
  mongodb_data:
  redis_data:

networks:
  rps-network:
    driver: bridge
